### ISSUE TITLE
potential misconfiguration between default nginx settings and express

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#4879]
```
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information on this error.
    at _Validations.<anonymous> (/Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:125:15)
    at _Validations.wrap (/Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:168:18)
    at _Validations.xForwardedForHeader (/Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:123:10)
    at Object.keyGenerator (/Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:365:19)
    at /Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:415:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/amann/work/saf/cloned-heimdall2/apps/backend/node_modules/express-rate-limit/dist/index.cjs:397:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
```

**Comment by rathbunr** [comment]
This bugs me because I am trying to clean up logging.  

1. Potential fix since the issue explicitly mentions Nginx (which is a single reverse proxy layer), the most secure and appropriate setting is 1, rather than true.
Recommended Patch:

JavaScript

// In your Express app initialization (likely apps/backend/src/main.ts or app.js)
app.set('trust proxy', 1);

Why 1?: This tells Express to trust exactly one hop—the Nginx server. It allows the application to see the real client IP (passed by Nginx) while preventing clients from spoofing IPs by manually adding their own X-Forwarded-For headers.

2. Location
Based on the stack trace in the issue (apps/backend/node_modules/...), you should apply this change in the backend application entry point.


The ERR_ERL_UNEXPECTED_X_FORWARDED_FOR error confirms the app is receiving proxy headers.

Setting trust proxy is the standard Express requirement for correct IP resolution behind Nginx.

This change restores accurate rate limiting and logging.

**Comment by Amndeep7** [comment]
@rathbunr I am currently unable to replicate that bug using the default nginx configuration with our default docker-compose using the latest release.  Can you provide me your configuration that is able to reproduce it?
